apiVersion: v1
kind: Service
metadata:
  name: {{ include "catwiki.fullname" . }}-admin
  labels:
    {{- include "catwiki.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.admin.service.port }}
      targetPort: 8001
      protocol: TCP
  selector:
    app.kubernetes.io/component: admin
    {{- include "catwiki.selectorLabels" . | nindent 4 }}
