{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "catwiki.fullname" . }}
  labels:
    {{- include "catwiki.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    # API 后端
    - host: {{ .Values.ingress.apiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "catwiki.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
    # 管理后台
    - host: {{ .Values.ingress.adminHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "catwiki.fullname" . }}-admin
                port:
                  number: {{ .Values.admin.service.port }}
    # 客户端
    - host: {{ .Values.ingress.clientHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "catwiki.fullname" . }}-client
                port:
                  number: {{ .Values.client.service.port }}
{{- end }}
