{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "catwiki.fullname" . }}-redis
  labels:
    {{- include "catwiki.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/component: redis
    {{- include "catwiki.selectorLabels" . | nindent 4 }}
---
{{- if .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "catwiki.fullname" . }}-redis
  labels:
    {{- include "catwiki.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.redis.persistence.storageClass }}
  storageClassName: {{ .Values.redis.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}
{{- end }}
