apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catwiki.fullname" . }}-secret
  labels:
    {{- include "catwiki.labels" . | nindent 4 }}
type: Opaque
stringData:
  # PostgreSQL
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  # Redis
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  # RustFS
  RUSTFS_ACCESS_KEY: {{ .Values.rustfs.accessKey | quote }}
  RUSTFS_SECRET_KEY: {{ .Values.rustfs.secretKey | quote }}
  # Backend JWT
  SECRET_KEY: {{ .Values.backend.secretKey | quote }}
